### ISSUE TITLE
More pets than one pet? Free movement?

### ISSUE THREAD

**Issue by filipstojakovic** [gabrielchl/intellij-pets#2]
Is it possible to have more than one pet at a time?
It you would be nice to make them move randomly when panel is not in focus or something line that

**Comment by gabrielchl** [comment]
hey @filipstojakovic 
the plug currently doesn't support having more than 1 pet on the screen at a time, will add that to my todo list!
the pet should move around when the panel is not focus, it sits by default and should occasionally move to a random spot / lie down, let me know if this somehow isn't the case  🤔

**Comment by filipstojakovic** [comment]
hey @gabrielchl I love your plugin!
Please add a dog if you can.
Yea I notice the occasional movement after a while. Maybe less movement is better after all, that way I don't lose focus as much.

**Comment by gabrielchl** [comment]
hello! I have good news! (hopefully)
I've finally found the time to rework the plugin from Java to Kotlin, and as part of that we've now got the ability to have multiple pets :)
As part of this change, it's now not possible to click on a pet and have it jump, but I don't think anyone's using this, it'll be re-introduced again in the future
![image](https://github.com/gabrielchl/intellij-pets/assets/5616556/02c1edd0-fde5-43bd-8220-206b976368e7)
