### ISSUE TITLE
Incompatible with WebStorm 2023.2

### ISSUE THREAD

**Issue by Arrow7000** [gabrielchl/intellij-pets#3]
When prompted to upgrade to WebStorm version 2023.2 it warns me that the Pets plugin is not compatible with that version. Would you be able to look into it and make Pets compatible with the latest version of WebStorm please? 🙏 I don't want to lose my pet cat 🐈  Thanks!

**Comment by gabrielchl** [comment]
Sure thing! I've released an update to bump the compatibility range version numbers, it's now pending staff review before public release, I'll let you know when that happens! :)

**Comment by gabrielchl** [comment]
The release has been approved! (https://plugins.jetbrains.com/plugin/21008-pets/versions)
:)
